### ISSUE TITLE
[Bug]: depyf.prepare_debug causes torch.compile crash with free var mismatch error

### ISSUE THREAD

**Issue by tombousso** [thuml/depyf#28] opened 2024-05-18 22:08 UTC
### Your current environment

transformer_engine (`docker run --gpus all -it nvcr.io/nvidia/pytorch:24.04-py3`)
and
latest depyf (`pip install depyf`)

### 🐛 Describe the bug

To reproduce:

```
import torch
torch.set_default_device('cuda')

from transformer_engine.pytorch.attention import DotProductAttention

model = DotProductAttention(32, 128)
args = (torch.ones([1, 256, 32, 128]),torch.ones([1, 256, 32, 128]),torch.ones([1, 256, 32, 128]))

model = torch.compile(model)
import depyf
with depyf.prepare_debug('debug_dir'):
    out = model.forward(*args)
```

Output:

```
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 616, in compile_inner
    assert code.co_freevars == out_code.co_freevars, msg
AssertionError: free var mismatch: old code object has free var ('data_ptr', 'last_dim_size', 'last_two_dims_size', 'shape', 'stride', 'qkv_format'), new code object has free var ('data_ptr', 'last_dim_size', 'last_two_dims_size', 'qkv_format', 'shape', 'stride')
```

Without `depyf.prepare_debug`, there are no errors, `torch.compile` succeeds.

**Comment by youkaichao** [comment] 2024-05-19 00:23
I believe this is because Dynamo generated bytecode does not obey some rules of Python. I filed a [PR](https://github.com/pytorch/pytorch/pull/126630) in the Pytorch repo, see how it works.

**Comment by youkaichao** [comment] 2024-05-19 08:01
Since this is quite a complicated issue, I would expect it might take a long time to resolve. Meanwhile, I find this problem is caused by this function:

https://github.com/NVIDIA/TransformerEngine/blob/67bc399d7ba7e49bf540746c1ef6a7e43eaed8f7/transformer_engine/pytorch/attention.py#L1902

It is used to calculate the layout of qkv, which should be a constant in your model.

You can try to print the qkv layout, and see if it is constant according to your code. If yes, you can remove this function:

```python
def _get_qkv_layout(
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        qkv_format: str = 'sbhd',
    ) -> str:
    return 'constant', q, k, v
```

Even when `torch.compile` can compile this function, it would introduce quite a lot overhead,  such as many graph breaks. In this case, I think such a modification would be beneficial.

**Comment by tombousso** [comment] 2024-05-20 17:29
I tested https://github.com/pytorch/pytorch/pull/126630 and indeed it fixes the crash.

Yes I agree there are too many graph breaks, definitely need to do some refactoring there.

Thanks again @youkaichao!

**Comment by youkaichao** [comment] 2024-05-20 17:36
I will try to work with pytorch team to fix that issue. Close this issue as it has been solved.

**Closed by youkaichao** 2024-05-20 17:36 UTC
Labels: bug

**Comment by youkaichao** [comment] 2024-05-23 05:12
This issue should be resolved once https://github.com/pytorch/pytorch/pull/126630 comes into public. Before that, in case anyone meets this issue again, nightly pytorch version with the PR https://github.com/pytorch/pytorch/pull/126630 is required.
